# Starter universe. The pipeline pools all tickers into one global training dataset.
STARTER_UNIVERSE = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "HINDUNILVR.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "TITAN.NS", "ASIANPAINT.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "JSWSTEEL.NS", "NTPC.NS", "POWERGRID.NS", "ONGC.NS",
    "COALINDIA.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS", "CIPLA.NS",
    "DRREDDY.NS", "APOLLOHOSP.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BAJAJ-AUTO.NS", "BAJAJFINSV.NS", "INDUSINDBK.NS", "ADANIENT.NS",
    "ADANIPORTS.NS", "HINDALCO.NS", "BPCL.NS", "BRITANNIA.NS", "GRASIM.NS",
    "TATACONSUM.NS", "TRENT.NS", "BEL.NS", "SHRIRAMFIN.NS", "LTIM.NS",
    "UPL.NS", "M&M.NS",
]
MARKET_TICKER = "^NSEI"
START_DATE = "2018-01-01"
END_DATE = None
HORIZON_DAYS = 5
